// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ReservarCanchas_ProyectoProgramacionIV.Migrations
{
    [DbContext(typeof(BaseDatos_ReservarCanchas_ProyectoProgramacionIV))]
    [Migration("20250427043704_Este es la primera migracion")]
    partial class Esteeslaprimeramigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Calendario", b =>
                {
                    b.Property<int>("CalendarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalendarioId"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NotasDetallada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("CalendarioId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Campus");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Cancha", b =>
                {
                    b.Property<int>("CanchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanchaId"));

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CanchaId");

                    b.ToTable("Cancha");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacultadId");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Facultad");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Implemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Implemento");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.PersonaUdla", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BannerId");

                    b.ToTable("PersonaUdla");

                    b.HasDiscriminator<string>("TipoPersona").HasValue("PersonaUdla");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonaUdlaId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("CanchaId");

                    b.HasIndex("PersonaUdlaId");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.ReservaImplemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<int>("ImplementoId")
                        .HasColumnType("int");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImplementoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaImplemento");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Administrador", b =>
                {
                    b.HasBaseType("ReservarCanchas_ProyectoProgramacionIV.Models.PersonaUdla");

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.HasIndex("FacultadId");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Estudiante", b =>
                {
                    b.HasBaseType("ReservarCanchas_ProyectoProgramacionIV.Models.PersonaUdla");

                    b.Property<int>("CarreraId")
                        .HasColumnType("int");

                    b.HasIndex("CarreraId");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.PersonalMantenimiento", b =>
                {
                    b.HasBaseType("ReservarCanchas_ProyectoProgramacionIV.Models.PersonaUdla");

                    b.HasDiscriminator().HasValue("PersonalMantenimiento");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Calendario", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Cancha", "Cancha")
                        .WithMany("Calendarios")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Reserva", null)
                        .WithMany("Calendarios")
                        .HasForeignKey("ReservaId");

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Carrera", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Facultad", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Campus", "Campus")
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Reserva", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.PersonaUdla", "PersonaUdla")
                        .WithMany()
                        .HasForeignKey("PersonaUdlaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("PersonaUdla");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.ReservaImplemento", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Implemento", "Implemento")
                        .WithMany()
                        .HasForeignKey("ImplementoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Reserva", "Reserva")
                        .WithMany("ReservaImplementos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Implemento");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Administrador", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Estudiante", b =>
                {
                    b.HasOne("ReservarCanchas_ProyectoProgramacionIV.Models.Carrera", "Carrera")
                        .WithMany()
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Cancha", b =>
                {
                    b.Navigation("Calendarios");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ReservarCanchas_ProyectoProgramacionIV.Models.Reserva", b =>
                {
                    b.Navigation("Calendarios");

                    b.Navigation("ReservaImplementos");
                });
#pragma warning restore 612, 618
        }
    }
}
